sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.1
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

gemfile:
  - spec/dummy/Gemfile

env:
  global:
    - RAILS_ENV=test
    - DRIVER=selenium_chrome
    - CHROME_BIN=/usr/bin/google-chrome
    - USE_COVERALLS=TRUE

install:
  - gem install rubocop
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - rake
